### ISSUE TITLE
ContainerAwareEventDispatcher is deprecated since Symfony 3.3

### ISSUE THREAD

**Issue by romantymoshyk** [glorpen/GlorpenPropelBundle#7]
Dear @glorpen,
could you update dependencies to be up to date with SF 3.3 ? SF is going to drop lazy load with ContainerAwareEventDispatcher and suggest to use EventDispatcher with closure-proxy injection instead.
http://symfony.com/doc/current/components/event_dispatcher/container_aware_dispatcher.html

**Comment by glorpen** [comment]
Sure, looks easy enough.

**Comment by glorpen** [comment]
Ended up with doing some cleanup; as of v1.5.0 tests are now passing for S2 4.x-dev.

**Comment by romantymoshyk** [comment]
Thank you very match! Glorpen is really awesome 👍
