### ISSUE TITLE
propelorm/PropelBundle v1.* not maintained

### ISSUE THREAD

**Issue by tjveldhuizen** [glorpen/GlorpenPropelBundle#8]
This bundle requires [propelorm/PropelBundle](https://github.com/propelorm/PropelBundle) v1.*, but according to https://github.com/propelorm/PropelBundle/pull/437#issuecomment-252769811 this branches are not maintained anymore. Is there any chance [glorpen/GlorpenPropelBundle](https://github.com/glorpen/GlorpenPropelBundle) will target the [3.0-branch](https://github.com/propelorm/PropelBundle/tree/3.0) of this bundle?

**Comment by glorpen** [comment]
If theirs readme is up to date, 3.0-branch of PropelBundle is using Propel2 (which itself is currently unmaintained). Supporting Propel1, 2 and now 3 all at once could be troublesome.
Also, I think Propel3 now has event listeners:
```
The repository pattern gives us the ability to hook during runtime into entity lifecycle events.
We have events like pre/post save/update/insert/commit.
```

So... there will be support for Propel2/3 when:
- stable version of Propel2/3 is released
- and there will be no way to do nice extending and add listeners to model events

Until then I'm open to PR's :)
